package org.zk.simplemybatis;


import org.junit.*;
import org.zk.simplemybatis.io.Resources;
import org.zk.test.dao.UserDao;
import org.zk.test.domain.User;

import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.List;


public class SqlSessionTest {

    static SqlSessionFactory sqlSessionFactory;
    SqlSession sqlSession;

    @BeforeClass
    public static void beforeClass() throws Exception {
        // 初始化数据
//        Connection connection = DriverManager.getConnection("jdbc:hsqldb:mem:mybatis", "sa", "");
//        Statement statement = connection.createStatement();
//        statement.execute("create table tb_user " +
//                "(id int generated by default as identity, username varchar(20), primary key(id))");
//        statement.execute("insert into tb_user(username) values('zk')");
//        statement.execute("insert into tb_user(username) values('zx')");
//        connection.close();
        // 创建SessionFactory
        InputStream inputStream = Resources.getResourceAsStream("mybatis.xml");
        sqlSessionFactory = new SqlSessionFactoryBuilder().build(inputStream);
    }

    @Before
    public void before() {
        sqlSession = sqlSessionFactory.openSession();
    }

    @After
    public void after() {
        sqlSession.close();
    }

    @Test
    public void testSelectList() {
        List<User> list = sqlSession.selectList("org.zk.test.dao.UserDao.findAll", null);
        Assert.assertEquals(2, list.size());
        Assert.assertEquals("zk", list.get(0).getUsername());
    }

    @Test
    public void testDao() {
        UserDao userDao = sqlSession.getMapper(UserDao.class);
        List<User> userList = userDao.findAll();
        System.out.println(userList);
//        Assert.assertEquals(2, userList.size());
//        Assert.assertEquals("zk", userList.get(0).getUsername());
    }


}
